### ISSUE TITLE
node create-symlinks.js causes error

### ISSUE THREAD

**Issue by EisenbergEffect** [angular/pipe#1]
My guess is that this has something to do with the fact that I'm running this on Windows 8.1. I was attempting to get `di.js` up and running by executing `npm install`. I received the following error info:

```
43203 info install pipe@0.0.0
43204 info postinstall pipe@0.0.0
43205 verbose unsafe-perm in lifecycle true
43206 info pipe@0.0.0 Failed to exec postinstall script
43207 info C:\Users\Rob\Documents\GitHub\di.js\node_modules\pipe unbuild
43208 info preuninstall pipe@0.0.0
43209 info uninstall pipe@0.0.0
43210 verbose true,C:\Users\Rob\Documents\GitHub\di.js\node_modules,C:\Users\Rob\Documents\GitHub\di.js\node_modules unbuild pipe@0.0.0
43211 info postuninstall pipe@0.0.0
43212 error pipe@0.0.0 postinstall: `node create-symlinks.js`
43212 error Exit status 8
43213 error Failed at the pipe@0.0.0 postinstall script.
43213 error This is most likely a problem with the pipe package,
43213 error not with npm itself.
43213 error Tell the author that this fails on your system:
43213 error     node create-symlinks.js
43213 error You can get their info via:
43213 error     npm owner ls pipe
43213 error There is likely additional logging output above.
43214 error System Windows_NT 6.2.9200
43215 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
43216 error cwd C:\Users\Rob\Documents\GitHub\di.js
43217 error node -v v0.10.22
43218 error npm -v 1.3.14
43219 error code ELIFECYCLE
43220 verbose exit [ 1, true ]
```

**Comment by EisenbergEffect** [comment]
It seems that `fs.symlinkSync` requires admin privileges on windows.

**Comment by EisenbergEffect** [comment]
Sorry, the actual error is coming from `fs.unlinkSync`. It happens on the second iteration, when trying to unlink gulp. Here's some details

```
Installing symlink C:\Users\Rob\Documents\GitHub\di.js\node_modules/karma -> pipe/node_modules/karma
C:\Users\Rob\Documents\GitHub\di.js\node_modules/gulp already exists, removing...

fs.js:760
  return binding.unlink(pathModule._makeLong(path));
                 ^
Error: EPERM, operation not permitted 'C:\Users\Rob\Documents\GitHub\di.js\node_modules\gulp'
    at Object.fs.unlinkSync (fs.js:760:18)
    at C:\Users\Rob\Documents\GitHub\di.js\node_modules\pipe\create-symlinks.js:24:8
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\Rob\Documents\GitHub\di.js\node_modules\pipe\create-symlinks.js:18:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
npm ERR! pipe@0.0.0 postinstall: `node create-symlinks.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the pipe@0.0.0 postinstall script.
npm ERR! This is most likely a problem with the pipe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node create-symlinks.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls pipe
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Rob\Documents\GitHub\di.js
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Rob\Documents\GitHub\di.js\npm-debug.log
npm ERR! not ok code 0
```

**Comment by vojtajina** [comment]
That's because it tries to remove the link if it already exists.

I guess we can ignore that (assuming that the existing file is the correct symlink).

**Comment by EisenbergEffect** [comment]
There's something else going wrong. I'll need to dig in more. For the time
being I forked and added some try/catch blocks so I could get the build
working.

On Mon, Feb 24, 2014 at 5:59 PM, Vojta Jina notifications@github.comwrote:

> That's because it tries to remove the link if it already exists.
> 
> I guess we can ignore that (assuming that the existing file is the correct
> symlink).
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/angular/pipe/issues/1#issuecomment-35951095
> .

## 

Rob Eisenberg,
President - Blue Spire
www.durandaljs.com
